### ISSUE TITLE
Systemd service

### ISSUE THREAD

**Issue by ilarikokko** [markusressel/barcode-server#143]
Hi!

This is awesome tool. Is it possible to run this in ubuntu systemd service? I want it to run automatically when PC reboots.

**Comment by ilarikokko** [comment]
Lol, got it working with these settings in systemd service file:

[Unit]
Description=Barcode Server
After=network.target

[Service]
User={USERNAME}
Group={USERNAME}
Type=simple
ExecStart=/home/{USERNAME}/venv/bin/barcode-server run
WorkingDirectory=/home/{USERNAME}/.config
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by markusressel** [comment]
Hi @ilarikokko, great you like the project! :heart: 

Looks like you already found as solution. Since I am not using it this way myself (and therefore cannot test itI would rather not include a systemd example, but I guess this issue can easily be found by others.

Feel free to open another issue if anything comes up. :nerd_face:
