### ISSUE TITLE
2D Barcodes (QR-Codes)

### ISSUE THREAD

**Issue by oezgan** [markusressel/barcode-server#73]
I was trying to create a local system scanning the QR-Code of the CovPass App with a USB 1D and 2D Barcode scanner and found your server very useful. 
Unfortunately there are (or were) two issues with that:
1-  Ubuntu 20.03 LTS the evdev key events for specific characters like "/" are not called `KEY_KPSLASH` they are called `KP_SLASH` instead. Due to that I was getting a lot of DEBUG messages like `"Unhandled key KP_EQUAL" `
2 - The second issue was that my scanner was transmitting some characters like the  `$` with a SHIFT + 4. 
I believe the reason for that is that this server was not designed to read QR-Codes but I might be wrong.
So  I edited the `keyevent_reader.py` and did a quick fix. It is working so I can create a pull request, I am not full time coder so you might be better at this then me...
So here is the Feature request please implement QR-Code readings as well... 

Attached is my "fixed" `keyevent_reader.py` as txt
[keyevent_reader.txt](https://github.com/markusressel/barcode-server/files/7634032/keyevent_reader.txt)
As I mentioned it is not very beautiful :) 
Thank you!

**Comment by markusressel** [comment]
Hey @oezgan, glad barcode-server is useful.
Tit you try just removing the `_KP` from the `startswith`?

Current:
```
elif event.keycode.startswith("KEY_KP"):
  if len(event.keycode) == 7:
    character = event.keycode[-1]
```

New:
```
elif event.keycode.startswith("KEY_"):
  if len(event.keycode) == 7:
    character = event.keycode[-1]
```

Maybe this works with more than I had anticipated.
I am not that familiar with keyboard keycode bindings and stuff. If this doesn't work, we can just use your code, looks find to me :)

**Comment by oezgan** [comment]
Hey @markusressel
I am afraid my changes are not that simple :-) 
first of all I moved the `elif`s one indent out such that they are part of the outer if... 
`            elif event.keycode == "KEY_SPACE":
                character = ' '
            elif event.keycode.startswith("KEY_KP"):
                if len(event.keycode) == 7:
                    character = event.keycode[-1]
            elif event.keycode == "KEY_ASTERISK":
                character = '*'`
and I removed all the `KP`s from the keycodes example:
Current:
`KEY_KPEQUAL`
New:
`KEY_EQUAL`

this solves the mentioned keycode problem.

I also created a dictionary with the US_EN keyboard mappings
`US_EN_UPPER_DICT = {
    "`": "~",
    "1":"!",
    "2": "@",
    "3": "#",
    "4": "$",
    "5": "%",
    "6": "^",
    "7": "&",
    "8": "*",
    "9": "(",
    "0": ")",
    "-": "_",
    "=": "+",
    ",": "<",
    ".": ">",
    "/": "?",
    ";": ":",
    "'": "\"",
    "\\": "|",
    "[": "{",
    "]": "{"
}`

at the end of the `_on_key_event` method I added the following:
` if self._shift or self._caps:
                character = character.upper()
                if character in US_EN_UPPER_DICT.keys():
                    character = US_EN_UPPER_DICT[character]`

this solves the problem that the barcode scanner delivers the `$` sign with `SHIFT+4` 
at least my barcode scanner delivers that with this combination. On my research (googling) I found out that almost all barcode readers (1D or 2D) deliver the characters as keyboard keypresses so this seems to make sense. 
As I said I am not a coder (anymore) and I do not know much about keycodes and mappings either. 
I believe though creating a dictionaries for ASCII Keycodes and then map them directly is the better way to go. 
I will try that out if I find the time... 
Also I believe a `dev.grab()`   before the loop will grant exclusive access to the scanner device... 

So here is my dilemma:
 * Should I modify your server for reading CovPass QR Codes into a DB  with the now working hot fix of mine ? 
or 
 * Should I modify the keyevent handler and then modify the server into a QR code server for CovPass 
 
:-) I also need time for this of course... 
Anyway for now it works for me

**Comment by markusressel** [comment]
@oezgan Sorry I forgot to answer this after merging.

Yes, I started this project because I wanted to read simple 2D barcodes, numbers only.
However, there is no reason to not support other types of barcodes as well.
As long as its only keypresses, it should be fairly straight forward to support other inputs.
I have not done any testing on this myself though, and probably wont in the near future, since I currently have no personal use case for this.

Not sure about storing scanned items into a DB, barcode-server was meant more as a relay than a database interface.
I don't want the burden of integrating a multitude of different database protocols into a simple barcode-server.
If that is a functionality you need, then I would suggest using another service application or writing one yourself, that receives the barcodes sent by barcode-server (via one of the supported methods) and stores then stores them into a DB and/or handles them otherwise. node-red would probably be an option here (although I don't use or like the project).
